### ISSUE TITLE
1.19.x Support?

### ISSUE THREAD

**Issue by OfficialCRUGG** [ApricotFarmer11/tubion-legacy#1]
It would be great for this mod to run on 1.19.x
I don't want to use a separate instance of Minecraft just for TubNet and already use other mods (some of which aren't even available for 1.18) and play on 1.19-only servers.
Generally, it's always best to use the newest version of Minecraft.

**Comment by TotallyNoCallum** [comment]
Already being worked on

![image](https://user-images.githubusercontent.com/114112457/207144244-3fffb506-9726-403b-864a-16dabe06ac86.png)

**Comment by ApricotFarmer11** [comment]
I'm just going to update the mod to 1.19.2 since people tend to use the latest version. I guess more people would adopt the mod more as well, so what's not to like :P
